
app:
  name: WhoAmI
  version: 1.0.0

paths:
  models: ./data/models
  training: ./data/training

face_detection:
  scale_factor: 1.1
  min_neighbors: 5
  min_size: [30, 30]

camera:
  width: 640
  height: 480